runtime: nodejs20
service: default

handlers:
- url: /
  static_files: dist/index.html
  upload: dist/index.html

- url: /assets/(.*)
  static_files: dist/assets/\1
  upload: dist/assets/(.*)

- url: /(.*)
  static_files: dist/index.html
  upload: dist/index.html